openapi: 3.0.0

info:
  title: boredapi.com APIs
  version: 1.0.0

paths:
  /api/activity:
    get:
      summary: Get a random activity
      responses:
        200:
          description: A random activity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
  /api/activity?type={type}:
    get:
      summary: Get a random activity by type
      parameters:
        - in: path
          name: type
          schema:
            type: string
            enum: [education, recreational, social, diy, charity, cooking, relaxation, music, busywork]
          required: true
          description: The type of activity
      responses:
        200:
          description: A random activity with the given type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
  /api/activity?participants={participants}:
    get:
      summary: Get a random activity by number of participants
      parameters:
        - in: path
          name: participants
          schema:
            type: integer
            minimum: 1
          required: true
          description: The number of participants
      responses:
        200:
          description: A random activity with the given number of participants
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'

components:
  schemas:
    Activity:
      type: object
      properties:
        activity:
          type: string
          description: Description of the queried activity
        accessibility:
          type: number
          description: A factor describing how possible an event is to do with 0 being the most accessible and 1 being the least accessible. Hence the value will be between 0 and 1.
        type:
          type: string
          description: Type of the activity. It will be one among ["education", "recreational", "social", "diy", "charity", "cooking", "relaxation", "music", "busywork"]
        participants:
          type: integer
          description: The number of people that this activity could involve
        price:
          type: number
          description: A factor describing the cost of the event with zero being free and 1 being very expensive. Hence the value will be between 0 and 1
        link:
          type: string
          description: Online link to the activity if available
        key:
          type: string
          description: A unique numeric id for the activity
